WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

GROUND_CLEARANCE = 25

PADDLE_WIDTH_FACTOR = 60 -- paddles of different width exist!
PADDLE_HEIGHT_FACTOR = 20

BALL_WIDTH = 20
BALL_HEIGHT = 20

BRICK_WIDTH = 60
BRICK_HEIGHT = 20
ROW_MARGIN = 50
COL_MARGIN = 100

ARROW_WIDTH = 40
ARROW_HEIGHT = 40
