WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

GROUND_CLEARANCE = 25

PADDLE_WIDTH_FACTOR = 60 -- paddles of different width exist!
PADDLE_HEIGHT_FACTOR = 20

BALL_WIDTH = 40
BALL_HEIGHT = 40

ARROW_WIDTH = 40
ARROW_HEIGHT = 40
